# Generated by Django 5.1.4 on 2024-12-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_image1_remove_project_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
